name = "notes-theme"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = "A minimal, custom Hugo theme based on no-style-please."
homepage = "https://github.com/badenglass/notes-theme"
tags = ["minimal", "clean", "notes"]
features = ["blog", "zettelkasten", "daily notes"]
min_version = "0.41.0"
